version: '3.3'

services:
  backend:
    build: .
    ports:
      - '8000:8000'
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  # On producrion database ports are not exposed, 'cause only backend should have access

  database:
    image: postgres:15.1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - internal

networks:
  internal:
    driver: bridge
